"use client";
import { useRef, useState, useTransition } from "react";
import { requestFlexibleWaitlist, myFlexibleWaitlist, cancelFlexibleRequest } from "./flexible-actions";
import { minutesToHHMM } from "@/lib/utils";
export function FlexiblePanel({ salonId, professionalId, serviceIds, date }: { salonId: string; professionalId: string; serviceIds: string[]; date: string }) {
  const request = useRef<{ fingerprint: string; id: string } | null>(null);
  const [pending, transition] = useTransition(); const [message, setMessage] = useState(""); const [items, setItems] = useState<Awaited<ReturnType<typeof myFlexibleWaitlist>>>([]);
  const run = (fn: () => Promise<unknown>) => transition(async () => { setMessage(""); try { await fn(); setItems(await myFlexibleWaitlist(salonId)); } catch (err) { setMessage(err instanceof Error ? err.message : "Não foi possível atualizar a fila."); } });
  return <details className="rounded-xl border border-border bg-card p-3" onToggle={e => { if (e.currentTarget.open) run(async () => {}); }}><summary className="min-h-11 cursor-pointer text-sm font-semibold">Lista de espera por período</summary><p className="mb-3 text-xs text-muted-foreground">Informe quando você pode vir. A equipe confirma um encaixe dentro deste período, pela ordem dos pedidos compatíveis. Este pedido é para o titular da conta.</p><form className="space-y-3" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); const mins = (key: string) => { const [h, m] = String(form.get(key)).split(":").map(Number); return h! * 60 + m!; }; run(async () => { const payload = { professionalId, serviceIds, fromDate: String(form.get("from")), toDate: String(form.get("to")), startMinutes: mins("fromTime"), endMinutes: mins("toTime") }; const fingerprint = JSON.stringify(payload); if (request.current?.fingerprint !== fingerprint) request.current = { fingerprint, id: crypto.randomUUID() }; await requestFlexibleWaitlist(salonId, { ...payload, id: request.current.id }); setMessage("Pedido registrado. Acompanhe a confirmação em seus agendamentos."); }); }}><div className="grid grid-cols-2 gap-3"><label className="text-sm">Da data<input required name="from" type="date" defaultValue={date} className="min-h-11 w-full rounded-lg border border-border bg-background px-2" /></label><label className="text-sm">Até a data<input required name="to" type="date" defaultValue={date} className="min-h-11 w-full rounded-lg border border-border bg-background px-2" /></label><label className="text-sm">A partir de<input required name="fromTime" type="time" defaultValue="09:00" className="min-h-11 w-full rounded-lg border border-border bg-background px-2" /></label><label className="text-sm">Terminar até<input required name="toTime" type="time" defaultValue="18:00" className="min-h-11 w-full rounded-lg border border-border bg-background px-2" /></label></div><button disabled={pending} className="min-h-11 rounded-lg bg-primary px-3 text-sm text-primary-foreground">Solicitar encaixe no período</button></form><p role="status" className="mt-2 text-sm">{message}</p><ul className="mt-3 divide-y divide-border">{items.map(i => <li key={i.id} className="py-2 text-xs">{i.fromDate} — {i.toDate} · {minutesToHHMM(i.startMinutes)}–{minutesToHHMM(i.endMinutes)} · {i.professional.user.name}<p>{i.status === "WAITING" ? "Aguardando" : i.status === "FULFILLED" ? "Encaixe confirmado" : "Retirado da fila"}</p>{i.status === "WAITING" && <button disabled={pending} className="min-h-11 underline" onClick={() => run(() => cancelFlexibleRequest(salonId, i.id))}>Retirar pedido</button>}</li>)}</ul></details>;
}
