import Link from "next/link";
import { notFound } from "next/navigation";
import { isHqEnabled, withHq } from "@/lib/hq/access";
import { getPlatformAdminContext } from "@/lib/platform-admin";
import { definition, definitions, money, type Row } from "@/lib/hq/catalog";
import * as queries from "@/lib/hq/queries";
import * as repo from "@/lib/hq/repository";
import { HqError, uuid } from "@/lib/hq/validation";
import { Editor, CommandButton, ConfirmPayment, FeedbackConvert } from "@/components/hq/editor";
import { Pipeline } from "@/components/hq/pipeline";
import { Heading, Badge, DataTable, Tabs, Timeline, displayDate } from "@/components/hq/shared";

type Params=Record<string,string|undefined>;
const financeTabs:[string,string][]=[["/hq/finance","Métricas"],["/hq/subscriptions","Assinaturas"],["/hq/payments","Pagamentos"],["/hq/payments?bucket=overdue","Inadimplência"]];
const supportTabs:[string,string][]=[["/hq/tickets","Tickets"],["/hq/bugs","Bugs"]];
const productTabs:[string,string][]=[["/hq/features","Feature requests"],["/hq/feedbacks","Feedbacks"]];
function Pagination({page,hasMore,params}:{page:number;hasMore:boolean;params:Params}) {
 const url=(p:number)=>"?"+new URLSearchParams({...Object.fromEntries(Object.entries(params).filter((e):e is [string,string]=>Boolean(e[1]))),page:String(p)});
 return <div className="hq-actions">{page>1&&<Link className="hq-button secondary" href={url(page-1)}>Anterior</Link>}<span>Página {page}</span>{hasMore&&<Link className="hq-button secondary" href={url(page+1)}>Próxima</Link>}</div>;
}
function Filter({params,cmm=false,statuses=[]}:{params:Params;cmm?:boolean;statuses?:string[]}) {
 return <form className="hq-filter"><label>Pesquisar<input name="q" defaultValue={params.q} placeholder="Nome ou estabelecimento"/></label>{statuses.length>0&&<label>Status<select name="status" defaultValue={params.status??""}><option value="">Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>}{cmm&&<><label>Cidade<input name="city" defaultValue={params.city}/></label><label>Segmento<input name="segment" defaultValue={params.segment}/></label><label>Financeiro<select name="financial" defaultValue={params.financial??""}><option value="">Todos</option><option>Em dia</option><option>Inadimplente</option></select></label><label>Risco<select name="risk" defaultValue={params.risk??""}><option value="">Todos</option>{["Baixo","Médio","Alto"].map(v=><option key={v}>{v}</option>)}</select></label><label>Prioridade<select name="priority" defaultValue={params.priority??""}><option value="">Todas</option>{["Baixa","Média","Alta","Crítica"].map(v=><option key={v}>{v}</option>)}</select></label><label>Relacionamento<select name="contact" defaultValue={params.contact??""}><option value="">Todos</option><option value="silent">Sem contato há 30 dias</option><option value="recent">Contato nos últimos 7 dias</option><option value="due">Contato previsto até hoje</option><option value="renewal">Renovação em até 7 dias</option></select></label></>}{params.bucket&&<input type="hidden" name="bucket" value={params.bucket}/>}<button className="hq-button secondary">Filtrar</button><Link href="?">Limpar filtros</Link></form>;
}
function AccountTable({rows,cmm}:{rows:Row[];cmm:boolean}) {
 if(!rows.length)return <div className="hq-empty"><h2>Nenhuma conta encontrada</h2><p>Cadastre um lead ou ajuste os filtros para começar o acompanhamento.</p></div>;
 return <div className="hq-table-wrap"><table><thead><tr><th>Estabelecimento / contato</th><th>Comercial</th><th>Financeiro</th><th>Último contato</th><th>Próximo contato</th>{cmm?<><th>Tickets / features</th><th>Pendências</th><th>Responsável</th><th>Risco / prioridade</th></>:<><th>Temperatura</th><th>Cidade / segmento</th></>}<th>Próxima ação</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={"/hq/"+(r.customerId?"customers/"+r.customerId:r.leadId?"leads/"+r.leadId:"accounts/"+r.id)}>{r.business}</Link><small>{r.name}</small></td><td><Badge value={r.customerStatus??r.stage??r.leadStatus}/></td><td><Badge value={r.financialStatus}/></td><td>{displayDate(r.lastContact)}</td><td>{displayDate(r.nextContact,true)}</td>{cmm?<><td>{r.tickets} / {r.features}</td><td>{r.pendingFollowups} follow-ups</td><td>{r.owner??"—"}</td><td><Badge value={r.risk}/> <Badge value={r.priority}/></td></>:<><td><Badge value={r.temperature}/></td><td>{r.city??"—"}<small>{r.segment}</small></td></>}<td>{r.nextAction??"—"}</td></tr>)}</tbody></table></div>;
}
async function Executive({finance=false}:{finance?:boolean}) {
 const {metrics:m,popular,recent}=await withHq(tx=>queries.dashboard(tx));
 const metric=(title:string,key:string,currency=false,hint?:string)=><div className="hq-metric" key={key}><span>{title}</span><strong>{currency?money(m[key]):m[key]}</strong>{hint&&<small>{hint}</small>}</div>;
 const attention:[number,string,string][]=[[m.followupsToday,"follow-ups para hoje","/hq/followups?bucket=today"],[m.followupsOverdue,"follow-ups atrasados","/hq/followups?bucket=overdue"],[m.delinquent,"clientes inadimplentes","/hq/cmm?financial=Inadimplente"],[m.criticalBugs,"bugs críticos abertos","/hq/bugs"],[m.trialsTomorrow,"testes terminam amanhã","/hq/subscriptions?status=Teste"]];
 return <><Heading title={finance?"Financeiro":"Visão executiva"} description={finance?"Assinaturas, recebimentos e saúde da receita.":"O que está acontecendo e onde sua atenção faz diferença."}><Link className="hq-button" href={finance?"/hq/payments/new":"/hq/leads/new"}>{finance?"Nova cobrança":"+ Novo lead"}</Link></Heading>{finance&&<Tabs links={financeTabs} current="/hq/finance"/>}<div className="hq-metrics">{metric("MRR","mrr",true,"Receita recorrente mensal normalizada")}{metric("Recebido no mês","received",true,"Pela data de pagamento")}{metric("A receber","pending",true,"Vencimento hoje ou futuro")}{metric("Receita atrasada","overdue",true,"Vencida e ainda não recebida")}</div>
 {finance?<><div className="hq-metrics">{metric("Clientes pagantes","paying")}{metric("Clientes inadimplentes","delinquent")}<div className="hq-metric">Ticket médio recorrente<strong>{money(m.paying?m.mrr/m.paying:0)}</strong></div><div className="hq-metric">Inadimplência · total de clientes<strong>{m.customersTotal?Math.round(m.delinquent/m.customersTotal*100):0}%</strong></div></div><section className="hq-panel"><h2>Como os valores são calculados</h2><p>MRR considera assinaturas ativas e inadimplentes, após descontos. Planos anuais são divididos por 12. Testes, pausas e cancelamentos ficam fora do MRR. Recebimentos usam a data de pagamento; pendências usam o vencimento. Não há cobrança automática.</p></section></>:<><div className="hq-grid"><section className="hq-panel hq-attention"><h2>Atenção necessária</h2>{attention.filter(a=>a[0]>0).map(([n,label,url])=><Link key={label} href={url}><span><b>{n}</b> {label}</span><span>↗</span></Link>)}{popular.filter(f=>f.count>=3).map(f=><Link key={f.id} href={"/hq/features/"+f.id}><span>{f.count} clientes pediram {f.title}</span><span>↗</span></Link>)}{!attention.some(a=>a[0]>0)&&!popular.some(f=>f.count>=3)&&<p>Nenhuma pendência prioritária identificada.</p>}</section><section className="hq-panel"><h2>Features mais solicitadas</h2>{popular.length?popular.map(f=><p key={f.id}><Link href={"/hq/features/"+f.id}>{f.title}</Link> <Badge value={f.count+" clientes"}/></p>):<p>Associe clientes às solicitações para identificar as prioridades do produto.</p>}</section></div><div className="hq-metrics">{metric("Total de leads","leads")}{metric("Leads novos","newLeads")}{metric("Leads quentes","hot")}{metric("Oportunidades abertas","opportunities")}{metric("Clientes ativos","active")}{metric("Clientes em teste","trial")}{metric("Clientes inadimplentes","delinquent")}{metric("Clientes cancelados","cancelled")}{metric("Follow-ups hoje","followupsToday")}{metric("Follow-ups atrasados","followupsOverdue")}{metric("Tickets abertos","tickets")}{metric("Bugs abertos","bugs")}{metric("Feature requests","features")}{metric("Atividades · últimos 7 dias","activities")}</div><section className="hq-panel"><h2>Atividades recentes</h2><Timeline rows={recent}/></section></>}</>;
}
export default async function HqPage({params,searchParams}:{params:Promise<{path:string[]}>;searchParams:Promise<Params>}) {
 await getPlatformAdminContext();if(!isHqEnabled())return null;
 const {path}=await params;const search=await searchParams;
 if(path.length>2)notFound();
 let entity=path[0];const id=path[1];
 const aliases:Record<string,string>={support:"tickets",product:"features"};
 entity=aliases[entity]??entity;
 if(entity==="dashboard"&&!id)return <Executive/>;
 if(entity==="finance"&&!id)return <Executive finance/>;
 if(entity==="agents"&&!id)return <><Heading title="Agentes" description="Sua futura equipe de operação assistida."/><div className="hq-grid">{["Agente Chefe","Vendas","Suporte","Produto","Follow-up"].map(name=><section className="hq-panel" key={name}><Badge value="Planejado"/><h2>{name}</h2><p>Execuções, decisões, mensagens, logs e alertas ficarão reunidos aqui.</p><small>Última execução: nenhuma</small></section>)}</div><section className="hq-panel"><h2>Conversa com o Agente Chefe</h2><p>Disponível em uma próxima etapa. Nenhum agente está ativo.</p></section></>;
 if(entity==="settings"&&!id)return <><Heading title="Configurações" description="Identidade e regras da central interna."/><section className="hq-panel"><h2>Everflare HQ</h2><p>Moeda: real brasileiro · Fuso: America/Sao_Paulo</p><p>Acesso: administradores globais autorizados.</p><p>Pagamentos: registro manual. Integrações e agentes ainda não ativados.</p><Link className="hq-button secondary" href="/plataforma">Gerenciar estabelecimentos</Link></section></>;
 if(entity==="pipeline"&&!id){const rows=await withHq(tx=>queries.pipeline(tx));return <><Heading title="Pipeline comercial" description="Da primeira conversa ao fechamento."><Link className="hq-button" href="/hq/opportunities/new">Nova oportunidade</Link></Heading><Pipeline rows={rows}/></>;}
 const page=Math.max(1,Number.parseInt(search.page??"1",10)||1);
 if(["cmm","crm","leads","customers"].includes(entity)&&!id){
 const result=await withHq(tx=>queries.accounts(tx,{...search,page,kind:entity}));
 const cmm=entity==="cmm";
 return <><Heading title={cmm?"Acompanhamento":entity==="crm"?"CRM":definition(entity).title} description={cmm?"Relacionamento, pendências e próximos passos por conta.":"Uma relação contínua, do primeiro contato ao cliente ativo."}><Link className="hq-button" href={"/hq/"+(entity==="customers"?"customers":"leads")+"/new"}>{entity==="customers"?"Novo cliente":"Novo lead"}</Link></Heading><Tabs links={cmm?[["/hq/cmm","Todas as contas"],["/hq/cmm?risk=Alto","Em risco"],["/hq/cmm?contact=silent","Sem contato"],["/hq/cmm?contact=due","Pendências"]]:[["/hq/leads","Leads"],["/hq/customers","Clientes"],["/hq/pipeline","Pipeline"],["/hq/activities","Atividades"],["/hq/followups","Follow-ups"]]} current={"/hq/"+entity}/><Filter params={search} cmm={cmm} statuses={["Aberto","Frio","Morno","Quente","Negociação","Teste","Ativo","Inadimplente","Pausado","Cancelado","Convertido","Perdido"]}/><AccountTable rows={result.rows} cmm={cmm}/><Pagination page={page} hasMore={result.hasMore} params={search}/></>;
 }
 if(!Object.hasOwn(definitions,entity))notFound();
 const def=definition(entity);
 if(id){
 if(id!=="new"&&!uuid.safeParse(id).success)notFound();
 let data;
 try{data=await withHq(async tx=>({options:await queries.options(tx),detail:id==="new"?null:await queries.detail(tx,entity,id)}));}catch(e){if(e instanceof HqError&&e.message==="Registro não encontrado.")notFound();throw e;}
 const record=data.detail?.record;
 if(!record)return <><Heading title={"Cadastrar "+def.singular.toLowerCase()} description="Organize os dados e registre o próximo passo."/><section className="hq-panel"><Editor entity={entity} options={data.options} initial={Object.fromEntries(Object.entries(search).filter((e):e is [string,string]=>Boolean(e[1])))}/></section></>;
 const account=data.detail!.account;
 const fields=(account&&entity!=="accounts"?[...definition("accounts").fields,...def.fields]:def.fields).filter(f=>!f.ref&&f.type!=="json"&&!["actorId","entityId","normalizedTitle"].includes(f.key));
 const values={...account,...record};
 return <><Heading title={String(account?.business??record.title??record.plan??def.singular)} description={account?String(account.name)+" · Perfil 360°":def.title}><Link className="hq-button secondary" href={"/hq/"+entity}>Voltar à lista</Link></Heading><section className="hq-panel"><dl className="hq-profile">{fields.map((f,i)=><div key={f.key+i}><dt>{f.label}</dt><dd>{f.type==="money"?money(Number(values[f.key])):["date","month","datetime"].includes(f.type)?displayDate(values[f.key],f.type==="datetime"):f.type==="select"?<Badge value={values[f.key]}/>:String(values[f.key]??"—")}</dd></div>)}</dl></section>
 {entity==="leads"&&record.status!=="Convertido"&&<section className="hq-panel"><h2>Conversão em cliente</h2><p>Preserva os contatos, as oportunidades e todo o histórico.</p><CommandButton command={{type:"convert",id:record.id}}>Converter em cliente</CommandButton></section>}
 {entity==="payments"&&record.status==="Pendente"&&<ConfirmPayment record={record}/>}
 {entity==="feedbacks"&&<FeedbackConvert record={record} options={data.options}/>}
 {!def.appendOnly&&!["bugCustomers","featureCustomers"].includes(entity)&&!(entity==="payments"&&record.status!=="Pendente")&&<details className="hq-panel"><summary>Editar {def.singular.toLowerCase()}</summary><Editor entity={entity} record={record} account={account} options={data.options}/></details>}
 {account&&<div className="hq-actions" style={{marginBottom:20}}><Link className="hq-button" href={"/hq/activities/new?accountId="+account.id}>Registrar contato</Link><Link className="hq-button secondary" href={"/hq/followups/new?accountId="+account.id}>Agendar follow-up</Link>{data.detail!.sections.customers?.[0]&&<Link className="hq-button secondary" href={"/hq/subscriptions/new?customerId="+data.detail!.sections.customers[0].id}>Nova assinatura</Link>}</div>}
 {entity==="subscriptions"&&<section className="hq-panel"><h2>Valor final</h2><strong>{money(Number(record.amountCents)-Number(record.discountCents))}</strong><p>Valor por período após o desconto.</p></section>}{entity==="features"&&<section className="hq-panel"><h2>{record.interestedCustomers} clientes interessados</h2><p>Primeira solicitação: {displayDate(record.firstRequest)} · Última: {displayDate(record.lastRequest)}</p></section>}{entity==="bugs"&&<section className="hq-panel"><h2>Associar cliente afetado</h2><Editor entity="bugCustomers" options={data.options} initial={{bugId:record.id}}/></section>}
 {entity==="features"&&<section className="hq-panel"><h2>Associar cliente interessado</h2><Editor entity="featureCustomers" options={data.options} initial={{featureId:record.id}}/></section>}
 {Object.entries(data.detail!.sections).filter(([key])=>!["leads","customers"].includes(key)).map(([key,rows])=><section className="hq-panel" key={key}><h2>{key==="activities"?"Histórico completo":definition(key).title}</h2>{key==="activities"?<Timeline rows={rows}/>:<DataTable entity={key} rows={rows} options={data.options}/>}</section>)}</>;
 }
 const {result,options}=await withHq(async tx=>({result:await repo.list(tx,entity,{...search,page}),options:await queries.options(tx)}));
 return <><Heading title={def.title} description="Registros, contexto e acompanhamento da operação."><Link className="hq-button" href={"/hq/"+entity+"/new"}>Cadastrar {def.singular.toLowerCase()}</Link></Heading>{["payments","subscriptions"].includes(entity)&&<Tabs links={financeTabs} current={"/hq/"+entity}/>} {["tickets","bugs"].includes(entity)&&<Tabs links={supportTabs} current={"/hq/"+entity}/>} {["features","feedbacks"].includes(entity)&&<Tabs links={productTabs} current={"/hq/"+entity}/>}
 {entity==="followups"&&<Tabs links={[["/hq/followups?bucket=today","Hoje"],["/hq/followups?bucket=overdue","Atrasados"],["/hq/followups?bucket=upcoming","Próximos"],["/hq/followups?status=Concluído","Concluídos"],["/hq/followups?status=Cancelado","Cancelados"]]}/>}
 <Filter params={search} statuses={[...(def.fields.find(f=>f.key==="status")?.options??[])]}/><DataTable entity={entity} rows={result.rows} options={options}/><Pagination page={page} hasMore={result.hasMore} params={search}/></>;
}
