import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { addDays, format, parseISO } from "date-fns";
import { ptBR } from "date-fns/locale";

test.describe("@database navegação compacta e calendário", () => {
  test.skip(!process.env.RUN_DATABASE_E2E, "Somente ambiente isolado com dados fictícios.");
  test("novo agendamento permite editar minutos pelo menu + em desktop e celular", async ({ page }) => {
    test.setTimeout(120_000);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/login");
    await page.getByLabel("Email").fill("dono@lunahair.com");
    await page.getByLabel("Senha", { exact: true }).fill("demo1234");
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
    await expect(page).toHaveURL(/\/(hoje|dashboard)$/, { timeout: 30_000 });
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      await page.goto("/agenda?date=2030-09-11");
      await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).click();
      await page.getByRole("menuitem", { name: /Novo agendamento/ }).click();
      const form = page.getByRole("dialog", { name: "Novo agendamento" });
      await form.getByLabel("Data", { exact: true }).fill("2030-09-12");
      for (const time of ["09:15", "10:45", "11:50"]) {
        await form.getByLabel("Hora de início").fill(time);
        await expect(form.getByLabel("Hora de início")).toHaveValue(time);
      }
      await expect(form.getByLabel("Data", { exact: true })).toHaveValue("2030-09-12");
      expect(await form.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
      expect((await new AxeBuilder({ page }).include('[role="dialog"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
      await form.screenshot({ path: test.info().outputPath(`agendamento-hora-livre-sintetico-${width}.png`) });
      await page.keyboard.press("Escape");
      await expect(form).not.toBeVisible();
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).click();
    await page.getByRole("menuitem", { name: /Novo bloqueio de horário/ }).click();
    const directBlock = page.getByRole("dialog", { name: "Bloquear disponibilidade" });
    await directBlock.getByLabel("Data de início", { exact: true }).fill("2030-09-12");
    await directBlock.getByLabel("Data de fim", { exact: true }).fill("2030-09-12");
    await directBlock.getByLabel("Hora de início", { exact: true }).fill("18:45");
    await directBlock.getByLabel("Hora de fim", { exact: true }).fill("19:30");
    await expect(directBlock.getByLabel("Hora de início", { exact: true })).toHaveValue("18:45");
    await directBlock.getByLabel("Motivo", { exact: true }).fill("Bloqueio sintético pelo menu +");
    await directBlock.getByRole("button", { name: "Revisar bloqueio" }).click();
    await expect(directBlock.getByText(/12\/09 18:45/)).toBeVisible();
    await directBlock.screenshot({ path: test.info().outputPath("bloqueio-1845-menu-mobile-sintetico.png") });
    await directBlock.getByRole("button", { name: "Confirmar bloqueio" }).click();
    await expect(directBlock.getByText(/Disponibilidade bloqueada/)).toBeVisible();
    await directBlock.getByRole("button", { name: "Concluir", exact: true }).click();
    // Independent grid regression: the pointer retains the five-minute segment.
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).click();
    await page.getByRole("menuitem", { name: /Selecionar intervalo/ }).click();
    const row = page.getByRole("button", { name: /^Selecionar bloqueio 18:30 com / }).first();
    await row.scrollIntoViewIfNeeded();
    const box = await row.boundingBox();
    await row.click({ position: { x: box!.width / 2, y: box!.height * 0.55 } });
    const block = page.getByRole("dialog", { name: "Bloquear disponibilidade" });
    await expect(block.getByLabel("Hora de início", { exact: true })).toHaveValue("18:45");
    await block.getByLabel("Hora de fim", { exact: true }).fill("19:30");
    await block.getByLabel("Motivo", { exact: true }).fill("Bloqueio sintético após atendimento");
    await block.getByRole("button", { name: "Revisar bloqueio" }).click();
    await expect(block.getByText("0 reserva(s) no intervalo", { exact: true })).toBeVisible();
    await block.getByRole("button", { name: "Confirmar bloqueio" }).click();
    await expect(block.getByText("Disponibilidade bloqueada. 0 reserva(s) continuam ativas.", { exact: true })).toBeVisible();
    expect(errors).toEqual([]);
  });
  test("recolhe e restaura o menu, muda a data e abre o calendário no celular", async ({ page }) => {
    test.setTimeout(120_000);
    const runtime: string[] = [];
    const hydration: string[] = [];
    page.on("pageerror", error => runtime.push(error.message));
    page.on("console", message => { if (["warning", "error"].includes(message.type()) && /hydrat|didn't match/i.test(message.text())) hydration.push(message.text()); });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto("/login");
    await page.getByLabel("Email").fill("dono@lunahair.com");
    await page.getByLabel("Senha", { exact: true }).fill("demo1234");
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
    await expect(page).toHaveURL(/\/(hoje|dashboard)$/, { timeout: 30_000 });
    await page.goto("/agenda");
    await expect(page.locator("[data-appointment-professional]").first()).toBeVisible();
    const professionalPalette = await page.locator("[data-pro-col]").evaluateAll(columns => columns.map(column => {
      const header = column.querySelector("[data-professional-color]")!;
      const color = getComputedStyle(header).borderBottomColor;
      return { id: column.getAttribute("data-pro-id"), color,
        matches: [...column.querySelectorAll("[data-appointment-professional]")].every(card => getComputedStyle(card).borderLeftColor === color) };
    }));
    expect(professionalPalette.length).toBeGreaterThan(1);
    expect(new Set(professionalPalette.map(pro => pro.color)).size).toBe(professionalPalette.length);
    expect(professionalPalette.every(pro => pro.matches)).toBe(true);
    await page.goto("/agenda?date=2026-09-06");
    const darkSidebar = page.getByRole("complementary", { name: "Menu do estabelecimento" });
    await expect(darkSidebar.getByRole("img", { name: "Everflair", exact: true })).toBeVisible();
    const themeBox = await darkSidebar.getByRole("button", { name: "Mudar para tema claro" }).boundingBox();
    const navBox = await darkSidebar.getByRole("navigation", { name: "Navegação principal" }).boundingBox();
    expect(themeBox!.y + themeBox!.height).toBeLessThan(navBox!.y);
    await page.screenshot({ path: test.info().outputPath("agenda-flair-escuro-expandido.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.getByRole("button", { name: "Mudar para tema claro" }).click();
    const lightPalette = await page.locator("[data-pro-col]").evaluateAll(columns => columns.map(column => ({
      id: column.getAttribute("data-pro-id"), color: getComputedStyle(column.querySelector("[data-professional-color]")!).borderBottomColor,
    })));
    expect(lightPalette).toEqual(professionalPalette.map(({ id, color }) => ({ id, color })));
    const sidebar = page.getByRole("complementary", { name: "Menu do estabelecimento" });
    await expect(sidebar.getByRole("img", { name: "Everflair", exact: true })).toBeVisible();
    await expect(sidebar.getByText("Painel de operação")).toHaveCount(0);
    await page.getByRole("button", { name: "Recolher menu", exact: true }).click();
    await expect(sidebar).toHaveAttribute("data-collapsed", "true");
    await expect(sidebar.getByRole("img", { name: "Everflair — símbolo Flair" })).toBeVisible();
    await page.reload();
    await expect(sidebar).toHaveAttribute("data-collapsed", "true");
    await expect(sidebar.getByRole("link", { name: "Agenda", exact: true })).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("agenda-lilas-profissionais.png"), animations: "disabled" });
    const calendar = page.getByRole("region", { name: "Calendário lateral" });
    await expect(calendar).not.toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    await calendar.getByRole("button", { name: "Avançar 1 semana", exact: true }).click();
    await expect(page).toHaveURL(/date=2026-09-13/);
    const next = format(addDays(parseISO("2026-09-13T12:00:00"), 1), "EEEE, d 'de' MMMM 'de' yyyy", { locale: ptBR });
    await calendar.getByRole("button", { name: next, exact: true }).click();
    await expect(page).toHaveURL(/date=2026-09-14/);
    await page.screenshot({ path: test.info().outputPath("agenda-lilas-menu-compacto.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.getByRole("button", { name: "Recolher calendário" }).click();
    await expect(calendar).not.toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    await expect(calendar).toBeVisible();
    await page.getByRole("button", { name: "Expandir menu", exact: true }).click();
    await expect(sidebar).toHaveAttribute("data-collapsed", "false");
    await page.setViewportSize({ width: 390, height: 844 });
    const gridBox = await page.locator(".agenda-grid").boundingBox();
    const weekStrip = await page.getByRole("navigation", { name: "Dias da semana da agenda" }).boundingBox();
    expect(weekStrip!.height).toBeLessThanOrEqual(70);
    expect(gridBox!.y - weekStrip!.height - 8).toBeLessThan(145);
    expect(gridBox!.height + weekStrip!.height + 8).toBeGreaterThan(620);
    const quickActionBox = await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).boundingBox();
    expect(quickActionBox!.y).toBeGreaterThan(700);
    expect(quickActionBox!.width).toBe(44);
    const dateControl = await page.getByRole("button", { name: "Abrir calendário", exact: true }).boundingBox();
    const viewControl = await page.getByRole("combobox", { name: "Visualização da agenda" }).boundingBox();
    const filterControl = await page.getByRole("button", { name: "Buscar e filtrar agenda" }).boundingBox();
    expect(Math.abs(dateControl!.y - viewControl!.y)).toBeLessThanOrEqual(4);
    expect(Math.abs(filterControl!.y - viewControl!.y)).toBeLessThanOrEqual(4);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole("button", { name: "Buscar e filtrar agenda" }).click();
    const filters = page.getByRole("dialog", { name: "Buscar e filtrar agenda" });
    await expect(filters.getByRole("button", { name: "Todos profissionais" })).toBeVisible();
    await filters.getByRole("button", { name: "Ver agenda", exact: true }).click();
    await expect(page.getByRole("button", { name: "Buscar e filtrar agenda" })).toBeFocused();
    await expect(page.getByRole("region", { name: "Marca e aparência" }).getByRole("button", { name: "Mudar para tema escuro" })).toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Escolher data" });
    await expect(dialog).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("agenda-calendario-mobile.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.keyboard.press("Escape");
    await expect(dialog).not.toBeVisible();
    await expect(page.getByRole("button", { name: "Abrir calendário", exact: true })).toBeFocused();
    expect(runtime).toEqual([]);
    expect(hydration).toEqual([]);
  });
});
