import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { addDays, format, parseISO } from "date-fns";
import { ptBR } from "date-fns/locale";

test.describe("@database navegação compacta e calendário", () => {
  test.skip(!process.env.RUN_DATABASE_E2E, "Somente ambiente isolado com dados fictícios.");
  test("recolhe e restaura o menu, muda a data e abre o calendário no celular", async ({ page }) => {
    test.setTimeout(120_000);
    const runtime: string[] = [];
    const hydration: string[] = [];
    page.on("pageerror", error => runtime.push(error.message));
    page.on("console", message => { if (["warning", "error"].includes(message.type()) && /hydrat|didn't match/i.test(message.text())) hydration.push(message.text()); });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto("/login");
    await page.getByLabel("Email").fill("dono@lunahair.com");
    await page.getByLabel("Senha", { exact: true }).fill("demo1234");
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
    await expect(page).toHaveURL(/\/(hoje|dashboard)$/, { timeout: 30_000 });
    await page.goto("/agenda");
    await expect(page.locator("[data-appointment-professional]").first()).toBeVisible();
    const professionalPalette = await page.locator("[data-pro-col]").evaluateAll(columns => columns.map(column => {
      const header = column.querySelector("[data-professional-color]")!;
      const color = getComputedStyle(header).borderBottomColor;
      return { id: column.getAttribute("data-pro-id"), color,
        matches: [...column.querySelectorAll("[data-appointment-professional]")].every(card => getComputedStyle(card).borderLeftColor === color) };
    }));
    expect(professionalPalette.length).toBeGreaterThan(1);
    expect(new Set(professionalPalette.map(pro => pro.color)).size).toBe(professionalPalette.length);
    expect(professionalPalette.every(pro => pro.matches)).toBe(true);
    await page.goto("/agenda?date=2026-09-06");
    const darkSidebar = page.getByRole("complementary", { name: "Menu do estabelecimento" });
    await expect(darkSidebar.getByRole("img", { name: "Everflair", exact: true })).toBeVisible();
    const themeBox = await darkSidebar.getByRole("button", { name: "Mudar para tema claro" }).boundingBox();
    const navBox = await darkSidebar.getByRole("navigation", { name: "Navegação principal" }).boundingBox();
    expect(themeBox!.y + themeBox!.height).toBeLessThan(navBox!.y);
    await page.screenshot({ path: test.info().outputPath("agenda-flair-escuro-expandido.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.getByRole("button", { name: "Mudar para tema claro" }).click();
    const lightPalette = await page.locator("[data-pro-col]").evaluateAll(columns => columns.map(column => ({
      id: column.getAttribute("data-pro-id"), color: getComputedStyle(column.querySelector("[data-professional-color]")!).borderBottomColor,
    })));
    expect(lightPalette).toEqual(professionalPalette.map(({ id, color }) => ({ id, color })));
    const sidebar = page.getByRole("complementary", { name: "Menu do estabelecimento" });
    await expect(sidebar.getByRole("img", { name: "Everflair", exact: true })).toBeVisible();
    await expect(sidebar.getByText("Painel de operação")).toHaveCount(0);
    await page.getByRole("button", { name: "Recolher menu", exact: true }).click();
    await expect(sidebar).toHaveAttribute("data-collapsed", "true");
    await expect(sidebar.getByRole("img", { name: "Everflair — símbolo Flair" })).toBeVisible();
    await page.reload();
    await expect(sidebar).toHaveAttribute("data-collapsed", "true");
    await expect(sidebar.getByRole("link", { name: "Agenda", exact: true })).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("agenda-lilas-profissionais.png"), animations: "disabled" });
    const calendar = page.getByRole("region", { name: "Calendário lateral" });
    await expect(calendar).not.toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    await calendar.getByRole("button", { name: "Avançar 1 semana", exact: true }).click();
    await expect(page).toHaveURL(/date=2026-09-13/);
    const next = format(addDays(parseISO("2026-09-13T12:00:00"), 1), "EEEE, d 'de' MMMM 'de' yyyy", { locale: ptBR });
    await calendar.getByRole("button", { name: next, exact: true }).click();
    await expect(page).toHaveURL(/date=2026-09-14/);
    await page.screenshot({ path: test.info().outputPath("agenda-lilas-menu-compacto.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.getByRole("button", { name: "Recolher calendário" }).click();
    await expect(calendar).not.toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    await expect(calendar).toBeVisible();
    await page.getByRole("button", { name: "Expandir menu", exact: true }).click();
    await expect(sidebar).toHaveAttribute("data-collapsed", "false");
    await page.setViewportSize({ width: 390, height: 844 });
    const gridBox = await page.locator(".agenda-grid").boundingBox();
    expect(gridBox!.y).toBeLessThan(145);
    expect(gridBox!.height).toBeGreaterThan(620);
    const quickActionBox = await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).boundingBox();
    expect(quickActionBox!.y).toBeGreaterThan(700);
    expect(quickActionBox!.width).toBe(44);
    const dateControl = await page.getByRole("button", { name: "Abrir calendário", exact: true }).boundingBox();
    const viewControl = await page.getByRole("combobox", { name: "Visualização da agenda" }).boundingBox();
    const filterControl = await page.getByRole("button", { name: "Buscar e filtrar agenda" }).boundingBox();
    expect(Math.abs(dateControl!.y - viewControl!.y)).toBeLessThanOrEqual(4);
    expect(Math.abs(filterControl!.y - viewControl!.y)).toBeLessThanOrEqual(4);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole("button", { name: "Buscar e filtrar agenda" }).click();
    const filters = page.getByRole("dialog", { name: "Buscar e filtrar agenda" });
    await expect(filters.getByRole("button", { name: "Todos profissionais" })).toBeVisible();
    await filters.getByRole("button", { name: "Ver agenda", exact: true }).click();
    await expect(page.getByRole("button", { name: "Buscar e filtrar agenda" })).toBeFocused();
    await expect(page.getByRole("region", { name: "Marca e aparência" }).getByRole("button", { name: "Mudar para tema escuro" })).toBeVisible();
    await page.getByRole("button", { name: "Abrir calendário", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "Escolher data" });
    await expect(dialog).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("agenda-calendario-mobile.png"), animations: "disabled" });
    expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
    await page.keyboard.press("Escape");
    await expect(dialog).not.toBeVisible();
    await expect(page.getByRole("button", { name: "Abrir calendário", exact: true })).toBeFocused();
    expect(runtime).toEqual([]);
    expect(hydration).toEqual([]);
  });
});
