import { expect, test } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import AxeBuilder from "@axe-core/playwright";
import { assertSafeDatabaseOperation } from "../../src/lib/database-safety";

test("@database busca completa, encaixe ao editar e bloqueio editável até meia-noite", async ({ page }) => {
  test.skip(!process.env.RUN_DATABASE_E2E, "Somente banco descartável.");
  test.setTimeout(240_000);
  assertSafeDatabaseOperation(process.env, { operation: "booksy-followup-e2e" });
  const db = new PrismaClient();
  const suffix = crypto.randomUUID().slice(0, 8);
  const date = test.info().retry ? "2032-08-13" : "2032-08-12";
  const nextDate = test.info().retry ? "2032-08-14" : "2032-08-13";
  const clientName = `ZZZ Busca ${suffix}`;
  const otherName = `Encaixe ${suffix}`;
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  try {
    const salon = await db.salon.findUniqueOrThrow({ where: { slug: "luna-hair" } });
    await db.clientProfile.createMany({ data: Array.from({ length: 305 }, (_, i) => ({ salonId: salon.id, name: `AAA Busca ${suffix} ${i}` })) });
    await db.clientProfile.create({ data: { salonId: salon.id, name: clientName, phone: "11912345678" } });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto("/login");
    await page.getByLabel("Email").fill("dono@lunahair.com");
    await page.getByLabel("Senha", { exact: true }).fill("demo1234");
    await page.getByRole("button", { name: "Entrar", exact: true }).click();
    await expect(page).toHaveURL(/\/(hoje|dashboard)$/, { timeout: 30_000 });
    await page.goto(`/agenda?date=${date}`);
    const openCreate = async () => {
      await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).click();
      await page.getByRole("menuitem", { name: /Novo agendamento/ }).click();
      return page.getByRole("dialog", { name: "Novo agendamento" });
    };
    let form = await openCreate();
    await expect(form.locator('select[name="clientId"] option').filter({ hasText: clientName })).toHaveCount(0);
    await form.getByLabel("Pesquisar cliente").fill(clientName);
    await expect(form.locator('select[name="clientId"] option').filter({ hasText: clientName })).toHaveCount(1);
    await form.getByLabel("Cliente", { exact: true }).selectOption({ label: `${clientName} — 11912345678` });
    await form.getByLabel("Hora de início").fill("10:00");
    await form.getByRole("checkbox", { name: /Corte feminino/ }).check();
    await form.getByRole("button", { name: "Confirmar", exact: true }).click();
    await expect(form).not.toBeVisible();
    form = await openCreate();
    await form.getByRole("button", { name: "Novo cliente", exact: true }).click();
    await form.getByLabel("Nome", { exact: true }).fill(otherName);
    await form.getByLabel("Hora de início").fill("12:00");
    await form.getByRole("checkbox", { name: /Corte feminino/ }).check();
    await form.getByRole("button", { name: "Confirmar", exact: true }).click();
    await expect(form).not.toBeVisible();
    await page.getByText(otherName, { exact: true }).first().click();
    const detail = page.getByRole("dialog", { name: otherName });
    await detail.getByRole("button", { name: /Editar/ }).click();
    await detail.getByLabel("Horário do agendamento").fill("10:30");
    await detail.getByRole("button", { name: "Salvar alterações" }).click();
    await detail.getByLabel("Motivo do encaixe").fill("Intervalo combinado de teste");
    await detail.getByRole("button", { name: "Confirmar encaixe" }).click();
    await expect(detail.getByText("Agendamento atualizado.")).toBeVisible();
    await detail.getByRole("button", { name: "Concluir" }).click();
    const before = await db.appointment.findMany({ where: { salonId: salon.id, client: { name: { in: [clientName, otherName] } } }, orderBy: { id: "asc" } });
    expect(before).toHaveLength(2);
    expect(before.some(a => a.isOverbooked)).toBe(true);
    await page.getByRole("button", { name: "Abrir ações rápidas da agenda" }).click();
    await page.getByRole("menuitem", { name: /Novo bloqueio de horário/ }).click();
    const blocking = page.getByRole("dialog", { name: "Bloquear disponibilidade" });
    await blocking.getByLabel("Hora de início").fill("08:30");
    await blocking.getByLabel("Data de fim").fill(nextDate);
    await blocking.getByLabel("Hora de fim").fill("00:00");
    await blocking.getByRole("button", { name: "Revisar bloqueio" }).click();
    await blocking.getByRole("button", { name: "Confirmar bloqueio" }).click();
    await expect(blocking.getByRole("status")).toContainText("Disponibilidade bloqueada");
    await blocking.getByRole("button", { name: "Concluir", exact: true }).click();
    const block = await db.timeOff.findFirstOrThrow({ where: { professionalId: before[0].professionalId, startAt: new Date(`${date}T11:30:00Z`) } });
    const trigger = page.getByRole("button", { name: /Abrir bloqueio de/ }).first();
    await trigger.click();
    const edit = page.getByRole("dialog", { name: "Bloqueio de horário", exact: true });
    await edit.getByRole("button", { name: "Editar bloqueio" }).click();
    await edit.getByLabel("Hora de início").fill("08:45");
    await edit.getByLabel("Motivo (opcional)").fill(`Editado ${suffix}`);
    for (const width of [320, 390, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      expect(await edit.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
      expect((await new AxeBuilder({ page }).include('[role="dialog"]').withTags(["wcag2a", "wcag2aa"]).analyze()).violations).toEqual([]);
      await edit.screenshot({ path: test.info().outputPath(`bloqueio-edicao-${width}.png`) });
    }
    await edit.getByRole("button", { name: "Salvar bloqueio" }).click();
    await expect(edit.getByRole("status")).toContainText("Bloqueio atualizado");
    await edit.getByRole("button", { name: "Concluir" }).click();
    const changed = await db.timeOff.findFirstOrThrow({ where: { professional: { salonId: salon.id }, reason: `Editado ${suffix}` } });
    // Only the clicked occurrence changes; the original booking rows remain byte-for-byte equal.
    expect(changed.startAt).toEqual(new Date(`${date}T11:45:00Z`));
    expect(changed.endAt).toEqual(new Date(`${nextDate}T03:00:00Z`));
    expect(await db.timeOff.count({ where: { id: changed.id } })).toBe(1);
    expect(await db.timeOff.findUnique({ where: { id: block.id } })).not.toBeNull();
    expect(await db.appointment.findMany({ where: { id: { in: before.map(a => a.id) } }, orderBy: { id: "asc" } })).toEqual(before);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: test.info().outputPath("agenda-bloqueio-encaixe-390.png") });
    expect(errors).toEqual([]);
  } finally { await db.$disconnect(); }
});
