"use client";
import { useRef, useState, useTransition } from "react";
import { addCareEntry, readCareEntries } from "./care-actions";
import { formatInTimeZone } from "date-fns-tz";
export function CarePanel({ appointmentId, timezone, writable }: { appointmentId: string; timezone: string; writable: boolean }) {
  const [entries, setEntries] = useState<Awaited<ReturnType<typeof readCareEntries>>>([]); const [pending, transition] = useTransition(); const [error, setError] = useState("");
  const requestId = useRef<string>();
  const load = () => transition(async () => { try { setEntries(await readCareEntries(appointmentId)); } catch { setError("Não foi possível carregar o histórico de cuidados."); } });
  return <details className="rounded-xl border border-border p-3" onToggle={e => { if (e.currentTarget.open) load(); }}><summary className="min-h-11 cursor-pointer text-sm font-semibold">Cuidados e fotos desta visita</summary><p className="mb-3 text-xs text-muted-foreground">Registro privado da equipe autorizada. Correções são novas anotações e preservam o original.</p>
    {writable && <form className="space-y-3" onSubmit={e => { e.preventDefault(); const element = e.currentTarget; const form = new FormData(element); requestId.current ??= crypto.randomUUID(); form.set("requestId", requestId.current); form.set("appointmentId", appointmentId); setError(""); transition(async () => { try { await addCareEntry(form); requestId.current = undefined; element.reset(); setEntries(await readCareEntries(appointmentId)); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível salvar."); } }); }}><label className="block text-sm">Procedimentos, produtos e orientações<textarea required minLength={3} maxLength={8000} name="body" rows={4} className="mt-1 w-full rounded-lg border border-border bg-background p-3" /></label><label className="block text-sm">Foto privada (opcional, até 800 KB)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" className="mt-1 block w-full text-xs" /></label><label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" name="photoConsent" />O cliente autorizou esta foto para o histórico de cuidados.</label><button disabled={pending} className="min-h-11 rounded-lg bg-[var(--action-positive)] px-3 text-sm text-white">Registrar cuidados</button></form>}
    {error && <p role="alert" className="text-sm text-danger">{error}</p>}<ul className="mt-3 divide-y divide-border">{entries.map(entry => <li key={entry.id} className="space-y-2 py-3"><p className="whitespace-pre-wrap text-sm">{entry.body}</p><p className="text-xs text-muted-foreground">{entry.authorName} · {formatInTimeZone(new Date(entry.createdAt), timezone, "dd/MM/yyyy HH:mm")}</p>{entry.photoConsent && <a className="inline-flex min-h-11 items-center text-sm underline" href={`/api/care-photo/${entry.id}`} target="_blank" rel="noreferrer">Abrir foto privada</a>}</li>)}</ul>{!entries.length && <p className="mt-3 text-xs text-muted-foreground">Nenhum cuidado registrado nesta visita.</p>}</details>;
}
