"use client";
import { useState, useTransition } from "react";
import { listFlexibleRequests, promoteFlexibleRequest } from "./flexible-actions";
import { minutesToHHMM, formatMoney } from "@/lib/utils";
export function FlexibleQueuePanel() {
  const [items, setItems] = useState<Awaited<ReturnType<typeof listFlexibleRequests>>>([]); const [pending, transition] = useTransition(); const [message, setMessage] = useState("");
  const run = (fn: () => Promise<unknown>) => transition(async () => { setMessage(""); try { await fn(); setItems(await listFlexibleRequests()); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível atualizar."); } });
  return <details className="mb-3 rounded-xl border border-border bg-card p-3" onToggle={e => { if (e.currentTarget.open) run(async () => {}); }}><summary className="min-h-11 cursor-pointer text-sm font-semibold">Pedidos de encaixe por período</summary><p className="text-xs text-muted-foreground">Ordem de chegada entre pedidos compatíveis. O horário, o recurso físico e o preço são conferidos novamente ao confirmar.</p><ul className="divide-y divide-border">{items.map((i, index) => <li key={i.id} className="space-y-2 py-3"><p className="text-sm font-semibold">{index + 1}. {i.client.name} · {i.professional.user.name}</p><p className="text-xs">{i.services.map(s => s.service.name).join(" + ")} · Catálogo: {formatMoney(i.services.reduce((n, s) => n + s.service.priceCents, 0))}</p><p className="text-xs text-muted-foreground">{i.fromDate} — {i.toDate}, das {minutesToHHMM(i.startMinutes)} até {minutesToHHMM(i.endMinutes)}</p><form className="flex flex-wrap items-end gap-2" onSubmit={e => { e.preventDefault(); const time = String(new FormData(e.currentTarget).get("start")); if (!window.confirm(`Confirmar um atendimento para ${i.client.name} em ${time.replace("T", " ")}? O valor seguirá o catálogo e as regras da data.`)) return; run(async () => { await promoteFlexibleRequest(i.id, time); setMessage("Encaixe confirmado e registrado no aplicativo do cliente."); }); }}><label className="text-xs">Horário do encaixe<input required name="start" type="datetime-local" min={`${i.fromDate}T${minutesToHHMM(i.startMinutes)}`} max={`${i.toDate}T23:59`} className="mt-1 block min-h-11 rounded-lg border border-border bg-background px-2 text-sm" /></label><button disabled={pending} className="min-h-11 rounded-lg bg-[var(--action-positive)] px-3 text-sm text-white">Confirmar encaixe</button></form></li>)}</ul>{!items.length && <p className="py-3 text-xs text-muted-foreground">Nenhum pedido ativo no período.</p>}<p role="status" className="text-sm">{message}</p></details>;
}
