"use client";
import { ArrowDownLeft, ArrowUpRight, Cake, Check, Clock3, Crown, MessageCircle, Smartphone, Star, Wallet } from "lucide-react";
import { ClientAppPreview } from "./client-app-preview";
import "./capabilities.css";

export function CapabilityShowcase() {
  return <section id="recursos" className="cp-section mk-wrap" aria-labelledby="capabilities-title">
    <div className="cp-heading"><p className="mk-eyebrow">MAIS QUE MARCAR HORÁRIOS</p><h2 id="capabilities-title">Do atendimento ao resultado.<br /><span>O negócio inteiro, conectado.</span></h2><p>A agenda é só o começo. Cuide das finanças, aproxime seus clientes e dê à equipe uma rotina mais organizada.</p></div>
    <article className="cp-row cp-finance"><div className="cp-copy"><span className="cp-number">01 / GESTÃO FINANCEIRA</span><Wallet size={25} strokeWidth={1.4} aria-hidden="true" /><h3>Entenda o que entra.<br />Planeje o que vem.</h3><p>Recebido, realizado e a receber têm significados diferentes. Veja cada um com clareza e acompanhe despesas, comissões e o fluxo de caixa por período.</p><ul><li><Check />Receitas e despesas no mesmo lugar</li><li><Check />Comissões e formas de pagamento</li><li><Check />Relatórios para acompanhar a operação</li></ul></div>
      <div className="cp-financial-visual"><div className="cp-window-heading"><Wallet size={18} /><span>Financeiro</span><span>Visão do período</span></div><div className="cp-finance-position"><span>UMA LEITURA MAIS CLARA</span><h4>Cada valor no seu lugar.</h4><div className="cp-money-row"><i><ArrowDownLeft /></i><div><strong>Recebido</strong><p>Pagamentos registrados</p></div><span>Caixa</span></div><div className="cp-money-row"><i><Check /></i><div><strong>Realizado</strong><p>Atendimentos concluídos</p></div><span>Operação</span></div><div className="cp-money-row"><i><Clock3 /></i><div><strong>A receber</strong><p>Reservas futuras ativas</p></div><span>Previsão</span></div></div><div className="cp-finance-bottom"><span>Despesas</span><span>Comissões</span><span>Fluxo de caixa</span></div><p className="cp-demo-note">Representação dos recursos de gestão financeira</p></div>
    </article>
    <article className="cp-row cp-client"><div className="cp-copy"><span className="cp-number">02 / APLICATIVO DO CLIENTE</span><Smartphone size={25} strokeWidth={1.4} aria-hidden="true" /><h3>Seu espaço.<br />Na palma da mão<br />de quem volta.</h3><p>Uma experiência para descobrir seus serviços, escolher um horário e acompanhar reservas. O cliente organiza a visita e a equipe acompanha tudo pela mesma agenda.</p><ul><li><Check />Serviços, equipe e agendamento online</li><li><Check />Reservas, remarcações e histórico</li><li><Check />Notificações e lembretes no aplicativo</li></ul><p className="cp-small-copy">Explore as telas para ver como o cliente encontra serviços e acompanha seus horários.</p></div><ClientAppPreview /></article>
    <article className="cp-row cp-marketing"><div className="cp-copy"><span className="cp-number">03 / MARKETING E RELACIONAMENTO</span><MessageCircle size={25} strokeWidth={1.4} aria-hidden="true" /><h3>O próximo atendimento<br />pode começar com<br />uma boa conversa.</h3><p>Encontre aniversariantes, clientes que não voltam há algum tempo e seus VIPs. Prepare mensagens pessoais e incentive avaliações e indicações.</p><ul><li><Check />Públicos organizados para cada campanha</li><li><Check />Mensagem revisada antes do contato</li><li><Check />Histórico de preparação das campanhas</li></ul><p className="cp-small-copy">Disponível a partir do plano Fundador. O envio pelo WhatsApp é iniciado manualmente pela equipe.</p></div>
      <div className="cp-marketing-visual"><div className="cp-window-heading"><MessageCircle size={18} /><span>Marketing</span><span>Relacionamento</span></div><div className="cp-campaigns">{[{icon:Cake,title:"Aniversariantes",text:"Uma mensagem na data certa."},{icon:Clock3,title:"Clientes ausentes",text:"Um convite para voltar."},{icon:Crown,title:"Clientes VIP",text:"Atenção a quem está sempre por perto."},{icon:Star,title:"Avaliações e indicações",text:"Seu trabalho apresentado por quem conhece."}].map(item=><div className="cp-campaign" key={item.title}><item.icon size={18} strokeWidth={1.5} /><div><strong>{item.title}</strong><p>{item.text}</p></div><ArrowUpRight size={14} aria-hidden="true" /></div>)}</div><div className="cp-campaign-flow"><span>Escolher público</span><ArrowUpRight /><span>Revisar mensagem</span><ArrowUpRight /><span>Abrir WhatsApp</span></div><p className="cp-demo-note">Etapas reais do módulo de marketing</p></div>
    </article>
  </section>;
}
