"use client";
import Image from "next/image";
import { useState } from "react";
import { Bell, CalendarDays, Clock3, Home, Search, ShoppingBag } from "lucide-react";
import { cn } from "@/lib/utils";

// Adapted from the existing public landing's client app demonstration.
// These are illustrative screens, not connected customer accounts.
export function ClientAppPreview() {
  const [screen, setScreen] = useState(0);
  const labels = ["Início", "Agendar", "Reservas", "Avisos"];
  return <div className="cp-app-demo"><div className="cp-phone-stage"><ClientPhone screen={screen} onPause={() => {}} /></div><div className="cp-screen-controls" role="group" aria-label="Explorar telas do aplicativo">{labels.map((label,index) => <button type="button" key={label} aria-pressed={screen===index} onClick={()=>setScreen(index)}>{label}</button>)}</div><p className="cp-demo-note">Aplicativo do cliente · demonstração ilustrativa</p></div>;
}
function PhoneShell({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) {
  return <div aria-hidden="true" className={cn("landing-phone-mockup relative mx-auto h-[640px] w-[306px] self-end rounded-t-[3rem] border p-2.5 shadow-[0_30px_70px_-28px_rgba(7,12,10,.45)]", dark ? "border-[#303138] bg-[#111216]" : "border-[#252932] bg-[#090b0f]")}><span className={cn("absolute left-1/2 top-4 z-30 h-6 w-24 -translate-x-1/2 rounded-full", dark ? "bg-[#22242a]" : "bg-[#1b1f27]")} /><div className="relative h-full overflow-hidden rounded-t-[2.35rem] bg-[#0e0f12]">{children}</div></div>;
}

function ClientPhone({ screen, onPause }: { screen: number; onPause: (paused: boolean) => void }) {
  return (
    <div onMouseEnter={() => onPause(true)} onMouseLeave={() => onPause(false)} className="self-end">
      <PhoneShell dark>
        {[<ClientHome key="home" />, <ClientBooking key="booking" />, <ClientReservations key="reservations" />, <ClientAlerts key="alerts" />].map((content, index) => <div key={index} aria-hidden={screen !== index} inert={screen !== index ? true : undefined} className={cn("absolute inset-x-0 bottom-[62px] top-0 overflow-hidden transition-opacity duration-300", screen === index ? "z-10 opacity-100" : "pointer-events-none opacity-0")}>{content}</div>)}
        <ClientNav active={screen} />
      </PhoneShell>
    </div>
  );
}

function ClientHome() {
  return <div className="h-full bg-[#0e0f12] px-3 pt-10 text-[#f8f5ef]">
    <div className="flex items-center gap-2 px-1"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e8ded0]/15 text-[9px] font-extrabold text-[#e8ded0]">EA</span><div className="min-w-0 flex-1"><small className="block text-[7px] uppercase tracking-wider text-[#8f9099]">Bem-vindo a</small><b className="block truncate text-[10px]">Espaço Aurora</b></div><span className="relative grid h-7 w-7 place-items-center rounded-full border border-[#2a2c32]"><ShoppingBag className="h-3.5 w-3.5" /><i className="absolute -right-1 -top-1 grid h-3.5 w-3.5 place-items-center rounded-full bg-[#e8ded0] text-[7px] not-italic text-black">2</i></span><span className="grid h-7 w-7 place-items-center rounded-full border border-[#2a2c32]"><Bell className="h-3.5 w-3.5" /></span></div>
    <div className="relative mt-4 h-[145px] overflow-hidden rounded-[1.4rem]"><Image src="/images/brand-mixed.webp" alt="Espaço Aurora, estabelecimento demonstrativo" fill quality={85} sizes="280px" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-transparent" /><div className="absolute bottom-3 left-3"><span className="rounded-full bg-[#e8ded0] px-2 py-1 text-[7px] font-bold text-black">MULTISSERVIÇOS</span><strong className="mt-1.5 block text-base">Espaço Aurora</strong><small className="text-[7px] text-white/75">Jardins · São Paulo</small></div></div>
    <div className="mt-3 rounded-[1.3rem] bg-[#e8ded0] p-3.5 text-[#0c130f]"><strong className="text-sm">Agendar um horário</strong><p className="my-1 text-[8px] opacity-70">Escolha o serviço e veja os horários disponíveis agora.</p><span className="inline-flex rounded-full bg-[#111418] px-3 py-2 text-[8px] font-bold text-[#e8ded0]">Agendar agora ↗</span></div>
    <div className="mt-2.5 grid grid-cols-2 gap-1.5 rounded-xl border border-[#292b31] bg-[#191a1f] p-2.5 text-[7px] text-[#a6a7ae]"><span className="flex gap-1"><Clock3 className="h-3 w-3 text-[#e8ded0]" />Aberto até 19:00</span><span>Cancelamento com 2h</span></div>
    <div className="mt-3 flex items-center justify-between px-1 text-[8px]"><b>Nossa equipe</b><span className="text-[#e8ded0]">Ver todos ›</span></div>
    <div className="mt-2 flex gap-2">{[["CM", "Camila", "Cabelo e cor"], ["BR", "Bruna", "Unhas e estética"]].map((person) => <div key={person[0]} className="flex-1 rounded-xl border border-[#292b31] bg-[#191a1f] p-2 text-center"><b className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-[#e8ded0]/20 text-[8px] text-[#e8ded0]">{person[0]}</b><small className="mt-1 block text-[8px]">{person[1]}</small><span className="block text-[6px] text-[#8f9099]">{person[2]}</span></div>)}</div>
    <div className="mt-2.5 flex items-center gap-2 rounded-full border border-[#292b31] bg-[#191a1f] px-3 py-2 text-[8px] text-[#8f9099]"><Search className="h-3 w-3" />Buscar serviços...</div>
  </div>;
}

function FlowHeader({ title }: { title: string }) { return <div className="flex items-center gap-3 px-4 pb-4 pt-12 text-white"><span className="grid h-7 w-7 place-items-center rounded-full border border-[#2b2d33]">‹</span><div><small className="block text-[7px] text-[#8f9099]">Espaço Aurora</small><b className="text-[12px]">{title}</b></div></div>; }

function ClientBooking() { return <div className="h-full bg-[#0e0f12] text-white"><FlowHeader title="Escolha os serviços" /><div className="mx-3 rounded-xl border border-[#e8ded0]/40 bg-[#e8ded0]/5 p-3"><b className="block text-[9px] text-[#e8ded0]">1 serviço escolhido</b><small className="text-[7px] text-[#8f9099]">Corte + tratamento</small></div><div className="mx-3 mt-3 flex items-center gap-2 rounded-full border border-[#292b31] bg-[#191a1f] px-3 py-2 text-[8px] text-[#8f9099]"><Search className="h-3 w-3" />Buscar corte, unha, massagem...</div><div className="mx-3 mt-2 flex gap-1.5 text-[7px]"><b className="rounded-full bg-[#e8ded0] px-2.5 py-1.5 text-black">Todos</b><span className="rounded-full border border-[#292b31] px-2.5 py-1.5">Cabelo</span><span className="rounded-full border border-[#292b31] px-2.5 py-1.5">Unhas</span></div><div className="mx-3 mt-3 grid grid-cols-2 gap-2">{[["Corte feminino", "50 min", "R$ 80"], ["Escova", "40 min", "R$ 55"], ["Manicure", "45 min", "R$ 45"], ["Massagem", "60 min", "R$ 120"]].map((service, index) => <article key={service[0]} className={cn("min-h-[105px] rounded-xl border bg-[#191a1f] p-2.5", index === 0 ? "border-[#e8ded0]" : "border-[#292b31]")}><i className={cn("ml-auto grid h-4 w-4 place-items-center rounded-full border text-[8px] not-italic", index === 0 ? "border-[#e8ded0] bg-[#e8ded0] text-black" : "border-[#34363d]")}>{index === 0 ? "✓" : ""}</i><b className="mt-2 block text-[9px] leading-tight">{service[0]}</b><small className="mt-1 block text-[7px] text-[#8f9099]">{service[1]}</small><strong className="mt-2 block text-[9px] text-[#e8ded0]">{service[2]}</strong></article>)}</div><div className="absolute inset-x-3 bottom-3 rounded-full bg-[#e8ded0] py-3 text-center text-[9px] font-bold text-black">Continuar · R$ 80</div></div>; }

function ClientReservations() { return <div className="h-full bg-[#0e0f12] text-white"><FlowHeader title="Minhas reservas" /><div className="mx-4 flex gap-4 border-b border-[#292b31] text-[8px]"><b className="border-b-2 border-[#e8ded0] pb-2 text-[#e8ded0]">Próximas</b><span>Histórico</span></div><article className="mx-3 mt-5 grid grid-cols-[48px_1fr] gap-3 rounded-2xl border border-[#292b31] bg-[#191a1f] p-3"><div className="rounded-xl bg-[#e8ded0]/10 p-2 text-center"><b className="block text-lg text-[#e8ded0]">18</b><small className="text-[7px]">AGO</small></div><div><span className="rounded-full bg-[#e8ded0]/15 px-2 py-1 text-[7px] text-[#e8ded0]">Confirmado</span><h4 className="mt-2 text-[10px]">Corte + hidratação</h4><p className="mt-1 text-[8px] text-[#b8b9be]">14:30 · Camila Mendes</p><small className="text-[7px] text-[#74767f]">Espaço Aurora · Jardins</small></div></article><div className="mx-3 flex justify-end gap-2 border-x border-b border-[#292b31] px-3 py-2 text-[8px]"><span>Ver detalhes</span><b className="text-[#e8ded0]">Remarcar</b></div><div className="mx-3 mt-5 rounded-2xl border border-[#292b31] p-4 text-center"><b className="text-[10px]">Tudo organizado</b><p className="mt-2 text-[8px] leading-relaxed text-[#8f9099]">Acompanhe horário, profissional e situação do atendimento em um só lugar.</p></div></div>; }

function ClientAlerts() { return <div className="h-full bg-[#0e0f12] text-white"><FlowHeader title="Notificações" /><div className="space-y-2 px-3">{[["Agendamento confirmado", "Seu horário de 18 de agosto, às 14:30, foi confirmado.", "Agora"], ["Lembrete do seu horário", "Amanhã você tem atendimento com Camila.", "Há 2 horas"], ["Conte como foi", "Seu atendimento foi concluído. Esperamos ver você novamente.", "12 de agosto"]].map((alert, index) => <article key={alert[0]} className={cn("flex gap-2.5 rounded-xl border p-3", index === 0 ? "border-[#e8ded0]/40 bg-[#e8ded0]/5" : "border-[#292b31] bg-[#191a1f]")}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#e8ded0]/15 text-[10px] text-[#e8ded0]">{index === 1 ? "↻" : index === 2 ? "★" : "✓"}</span><div><b className="text-[9px]">{alert[0]}</b><p className="my-1 text-[8px] leading-relaxed text-[#a3a4ab]">{alert[1]}</p><small className="text-[7px] text-[#666870]">{alert[2]}</small></div></article>)}</div></div>; }

function ClientNav({ active }: { active: number }) { const items = [{ icon: Home, label: "Início", index: 0 }, { icon: ShoppingBag, label: "Loja", index: -1 }, { icon: CalendarDays, label: "Agendar", index: 1 }, { icon: CalendarDays, label: "Reservas", index: 2 }, { icon: Bell, label: "Notificações", index: 3 }]; return <div className="absolute inset-x-0 bottom-0 z-20 grid h-[62px] grid-cols-5 border-t border-[#2a2b31] bg-[#191a1f] px-1 text-[#8f9099]">{items.map((item) => <span key={item.label} className={cn("grid place-content-center justify-items-center gap-1 text-[6px]", item.index === active && "text-[#e8ded0]")}><item.icon className={cn("h-4 w-4", item.label === "Agendar" && "rounded-full bg-[#e8ded0] p-0.5 text-black")} />{item.label}</span>)}</div>; }
