/** Conteúdo técnico versionado; mudanças exigem revisão das fontes do produto. */
export const knowledgeVersion = "2026-09-11-v1";
export type KnowledgeArticle = { id: string; title: string; terms: string[]; body: string; source: string; humanOnly?: boolean };
export const knowledgeArticles: KnowledgeArticle[] = [
 {id:"horarios",title:"Expediente, pausas e folgas",terms:["horario","expediente","pausa","folga","disponibilidade"],body:"Confira o horário do estabelecimento e a jornada de cada profissional. Pausas, folgas e bloqueios também afetam a disponibilidade. O proprietário pode ajustar o horário geral sem substituir as jornadas; para substituir jornadas, precisa selecionar explicitamente os profissionais e revisar a mudança. Uma pausa não deve ser confundida com um bloqueio pontual.",source:"docs/AGENDA_JORNADAS_2026-09-09.md"},
 {id:"bloqueios",title:"Bloqueios e encaixes na agenda",terms:["bloqueio","bloqueado","encaixe","pausa","conflito"],body:"Dono ou gerente pode abrir um bloqueio pela agenda e revisar antes de reabrir o intervalo. Encaixe durante pausa exige ação explícita de quem tem permissão. O agendamento público continua respeitando pausas e bloqueios. Não prometa que um horário está disponível sem conferência na agenda.",source:"docs/STATUS_ATUAL.md"},
 {id:"agendamento",title:"Agendamento público e conta do cliente",terms:["agendamento","agendar","catalogo","login","conta","reserva"],body:"O catálogo público pode ser consultado antes do login. Para confirmar uma reserva, entrar na fila e consultar dados pessoais, o cliente precisa entrar na conta do estabelecimento. Disponibilidade e valores são conferidos no servidor ao confirmar. Não pedir senha ao cliente nem criar reservas em nome dele pelo suporte.",source:"docs/DECISOES_PRODUTO.md"},
 {id:"cancelamento",title:"Cancelamento e reagendamento",terms:["cancelamento","cancelar","remarcar","reagendamento","reserva"],body:"Cancelamentos e reagendamentos preservam o histórico. No aplicativo do cliente, as alterações dependem do prazo configurado pelo estabelecimento. Depois do prazo, orientar contato com a equipe. Reagendamento confere conflitos, profissional, duração e disponibilidade. Não confirmar cancelamento ou remarcação pelo suporte sem ação efetiva na agenda.",source:"docs/DECISOES_PRODUTO.md"},
 {id:"precos",title:"Preço fixo ou a partir de",terms:["preco","valor","partir","servico","catalogo"],body:"Serviços podem ser apresentados com preço fixo ou a partir de. O catálogo informa a modalidade. Uma reserva preserva os dados e o preço registrados naquele momento. Dúvidas sobre o preço cobrado pelo salão devem ser conferidas com o estabelecimento; suporte do Everflare não concede descontos em nome dele.",source:"docs/PRECOS_VARIAVEIS_CONFIGURACOES_2026-09-10.md"},
 {id:"financeiro",title:"Recebimentos e operação financeira",terms:["financeiro","pagamento","recebimento","comanda","estorno","cobranca"],body:"Previsto, realizado e recebido são métricas diferentes. Um serviço concluído não significa pagamento recebido. Confirmações de recebimento são ações da equipe autorizada. Suporte não confirma pagamentos, concede descontos, estorna valores ou altera assinaturas. Casos financeiros precisam de revisão humana.",source:"docs/DECISOES_PRODUTO.md",humanOnly:true},
 {id:"comercial",title:"Planos, preços do SaaS e promessas comerciais",terms:["plano","mensalidade","assinatura","desconto","trial","teste gratis","integracao","prazo"],body:"Valores de planos, descontos, duração de teste, integrações e prazos de entrega precisam de confirmação do responsável pelo Everflare. Não inferir condições comerciais a partir de registros vazios. Encaminhar para revisão humana sem prometer preço, prazo ou funcionalidade.",source:"docs/HQ_SUPORTE_PILOTO.md",humanOnly:true},
 {id:"incidentes",title:"Relatos de erro e pedidos de funcionalidade",terms:["erro","bug","falha","problema","funcionalidade","sugestao","recurso"],body:"Solicite descrição do que ocorreu, passos para reproduzir e resultado esperado. Prints devem ocultar dados pessoais; esta fase aceita somente texto. Diferencie dúvida, possível bug e funcionalidade solicitada. Pesquise itens existentes antes de associar o cliente. Não prometa correção ou prazo antes de revisão humana.",source:"docs/EVERFLARE_HQ.md",humanOnly:true},
];
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export function searchKnowledge(question:string):KnowledgeArticle[] {
 const text=normalize(question);
 return knowledgeArticles.map(article=>({article,score:article.terms.filter(term=>text.includes(term)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.article.id.localeCompare(b.article.id)).slice(0,4).map(x=>x.article);
}
