import { beforeAll, describe, expect, it, vi } from 'vitest';
vi.setConfig({ testTimeout: 180_000, hookTimeout: 180_000 });
import type { AgendaScenario } from '../../../packages/salon-secretary/evaluation/agenda-practice-lib';
import { foldWords } from '../../../packages/salon-secretary/evaluation/agenda-practice-stats';
import { generateSplit, loadPools, namesJsonTokens, sidePools } from '../../../packages/salon-secretary/evaluation/multi-salon/generate';

// Review fix (rotated holdout names): the v3 HOLDOUT side never draws a person, surname or nickname sharing a folded token with
// ANY names.json entry, whatever the caller excludes (cohort compounds such as "Maria X" reuse names.json words). Names only.
const pools = loadPools(), v1 = namesJsonTokens(pools);
const tokensOf = (names: string[]) => [...new Set(names.flatMap(foldWords))];
const shared = (names: string[]) => tokensOf(names).filter(t => v1.has(t));

describe('v3 holdout name pool is disjoint from names.json by construction', () => {
  it('the cohort itself does share names.json words (compounds): the exclusion is needed', () => {
    const cohort = ['female', 'male', 'unisex', 'compound', 'foreignOrigin', 'wordNames'].flatMap(g => ((pools.cohort as unknown as Record<string, { name: string }[]>)[g] ?? []).map(p => p.name));
    expect(shared(cohort).length).toBeGreaterThan(0);
    for (const t of ['maria', 'valentina', 'cristina', 'lorenzo']) expect(v1.has(t), t).toBe(true);
  });
  it('with NO caller exclusion the holdout side has no names.json token (persons, surnames, nicknames); the dev side is unchanged', () => {
    const h = sidePools(pools, 'holdout', new Set(), { v3: true, retire: true });
    expect(shared(h.persons.map(p => p.name))).toEqual([]); expect(shared(h.surnames.map(s => s.name))).toEqual([]); expect(shared(h.nicknames.map(n => n.nickname))).toEqual([]);
    expect(h.persons.length).toBeGreaterThan(80); expect(h.excluded).toBe(v1.size);
    // the dev side still draws the dev half of names.json (a v3 DEV split is regenerated byte for byte: multi-salon-generator.test.ts)
    const d = sidePools(pools, 'dev', new Set(), { v3: true });
    expect(shared(d.persons.map(p => p.name)).length).toBeGreaterThan(0); expect(d.excluded).toBe(0);
    // v1 pools (ft-export, example names) are untouched
    expect(sidePools(pools, 'holdout').persons.some(p => foldWords(p.name).some(w => v1.has(w)))).toBe(true);
  });
  describe('a generated holdout (rotation waived for this in-memory test only)', () => {
    let held: AgendaScenario[];
    beforeAll(() => { held = generateSplit({ split: 'holdout', seed: 'names-disjoint-test', exclude: new Set(), rotation: 'waived-for-tests' }).scenarios; }, 180_000);
    it('names no customer or professional with a names.json word', () => {
      const people = held.flatMap(s => [...(s.customers ?? []).map(c => c.name), ...(s.professionals ?? []).map(p => p.name)]);
      expect(people.length).toBeGreaterThan(40);
      expect(shared(people)).toEqual([]);
    });
  });
});
