"use client";
import { useState, useTransition } from "react";
import { createResource, listResources, setResourceActive } from "./resource-actions";
export function ResourcePanel() {
  const [items, setItems] = useState<Awaited<ReturnType<typeof listResources>>>([]);
  const [pending, transition] = useTransition(); const [error, setError] = useState("");
  const run = (fn: () => Promise<unknown>) => transition(async () => { setError(""); try { await fn(); setItems(await listResources()); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível salvar."); } });
  return <details className="rounded-xl border border-border bg-card p-4" onToggle={e => { if (e.currentTarget.open) run(async () => {}); }}><summary className="min-h-11 cursor-pointer text-sm font-semibold">Salas e equipamentos</summary><p className="mb-3 text-xs text-muted-foreground">Cadastre cada unidade física e vincule ao serviço. Duas reservas não podem ocupar o mesmo recurso ao mesmo tempo.</p><form className="flex flex-wrap items-end gap-2" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); run(() => createResource({ name: String(form.get("resourceName")), kind: String(form.get("kind")) })); }}><label className="flex-1 text-sm">Nome<input required name="resourceName" minLength={2} maxLength={100} placeholder="Ex.: Sala 1, laser 1" className="mt-1 min-h-11 w-full rounded-lg border border-border bg-background px-3" /></label><label className="text-sm">Tipo<select name="kind" className="mt-1 block min-h-11 rounded-lg border border-border bg-background px-3"><option value="ROOM">Sala</option><option value="EQUIPMENT">Equipamento</option></select></label><button disabled={pending} className="min-h-11 rounded-lg bg-[var(--action-positive)] px-3 text-sm text-white">Adicionar recurso</button></form><ul className="mt-3 divide-y divide-border">{items.map(i => <li key={i.id} className="flex items-center justify-between gap-3 py-2 text-sm"><span>{i.name} · {i.kind === "ROOM" ? "Sala" : "Equipamento"} · {i.active ? "Ativo" : "Inativo"}</span><button disabled={pending} className="min-h-11 px-3 underline" onClick={() => run(() => setResourceActive(i.id, !i.active))}>{i.active ? "Desativar" : "Reativar"}</button></li>)}</ul>{error && <p role="alert" className="text-sm text-danger">{error}</p>}</details>;
}
